[package]
name = "gorillas"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
bevy = "0.13.2"
bevy_prototype_lyon = "0.11.0"
bevy_kira_audio = {version = "0.19.0", default-features = false, features = ["mp3"]}
iyes_perf_ui = "0.2.3"
